#!/usr/bin/env python3
"""Expand countries and plant monographs for The Herbalists Tome."""
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "public" / "data"
PLANTS_DIR = DATA / "plants"

COUNTRIES = [
    # Europe
    ("de", "europe", "Germany", "Deutschland", "de"),
    ("fr", "europe", "France", "Frankreich", "fr"),
    ("it", "europe", "Italy", "Italien", "it"),
    ("es", "europe", "Spain", "Spanien", "es"),
    ("at", "europe", "Austria", "Österreich", "at"),
    ("gr", "europe", "Greece", "Griechenland", "gr"),
    ("gb", "europe", "United Kingdom", "Vereinigtes Königreich", "gb"),
    ("ch", "europe", "Switzerland", "Schweiz", "ch"),
    ("pl", "europe", "Poland", "Polen", "pl"),
    ("pt", "europe", "Portugal", "Portugal", "pt"),
    ("nl", "europe", "Netherlands", "Niederlande", "nl"),
    ("se", "europe", "Sweden", "Schweden", "se"),
    ("no", "europe", "Norway", "Norwegen", "no"),
    ("ie", "europe", "Ireland", "Irland", "ie"),
    ("hu", "europe", "Hungary", "Ungarn", "hu"),
    ("cz", "europe", "Czechia", "Tschechien", "cz"),
    ("hr", "europe", "Croatia", "Kroatien", "hr"),
    ("tr", "europe", "Türkiye", "Türkei", "tr"),
    ("fi", "europe", "Finland", "Finnland", "fi"),
    ("ru", "europe", "Russia", "Russland", "ru"),
    # Asia
    ("in", "asia", "India", "Indien", "in"),
    ("cn", "asia", "China", "China", "cn"),
    ("kr", "asia", "South Korea", "Südkorea", "kr"),
    ("th", "asia", "Thailand", "Thailand", "th"),
    ("jp", "asia", "Japan", "Japan", "jp"),
    ("vn", "asia", "Vietnam", "Vietnam", "vn"),
    ("id", "asia", "Indonesia", "Indonesien", "id"),
    ("my", "asia", "Malaysia", "Malaysia", "my"),
    ("ph", "asia", "Philippines", "Philippinen", "ph"),
    ("lk", "asia", "Sri Lanka", "Sri Lanka", "lk"),
    ("np", "asia", "Nepal", "Nepal", "np"),
    ("ir", "asia", "Iran", "Iran", "ir"),
    ("il", "asia", "Israel", "Israel", "il"),
    ("sa", "asia", "Saudi Arabia", "Saudi-Arabien", "sa"),
    # North America
    ("us", "north-america", "United States", "Vereinigte Staaten", "us"),
    ("mx", "north-america", "Mexico", "Mexiko", "mx"),
    ("ca", "north-america", "Canada", "Kanada", "ca"),
    ("gt", "north-america", "Guatemala", "Guatemala", "gt"),
    ("cu", "north-america", "Cuba", "Kuba", "cu"),
    ("jm", "north-america", "Jamaica", "Jamaika", "jm"),
    # South America
    ("ar", "south-america", "Argentina", "Argentinien", "ar"),
    ("br", "south-america", "Brazil", "Brasilien", "br"),
    ("pe", "south-america", "Peru", "Peru", "pe"),
    ("co", "south-america", "Colombia", "Kolumbien", "co"),
    ("cl", "south-america", "Chile", "Chile", "cl"),
    ("bo", "south-america", "Bolivia", "Bolivien", "bo"),
    ("ec", "south-america", "Ecuador", "Ecuador", "ec"),
    ("py", "south-america", "Paraguay", "Paraguay", "py"),
    # Africa
    ("za", "africa", "South Africa", "Südafrika", "za"),
    ("so", "africa", "Somalia", "Somalia", "so"),
    ("eg", "africa", "Egypt", "Ägypten", "eg"),
    ("ma", "africa", "Morocco", "Marokko", "ma"),
    ("et", "africa", "Ethiopia", "Äthiopien", "et"),
    ("ng", "africa", "Nigeria", "Nigeria", "ng"),
    ("ke", "africa", "Kenya", "Kenia", "ke"),
    ("gh", "africa", "Ghana", "Ghana", "gh"),
    ("tn", "africa", "Tunisia", "Tunesien", "tn"),
    ("mg", "africa", "Madagascar", "Madagaskar", "mg"),
    ("sn", "africa", "Senegal", "Senegal", "sn"),
    ("bf", "africa", "Burkina Faso", "Burkina Faso", "bf"),
    ("sd", "africa", "Sudan", "Sudan", "sd"),
    ("ye", "asia", "Yemen", "Jemen", "ye"),
    # Oceania
    ("au", "oceania", "Australia", "Australien", "au"),
    ("nz", "oceania", "New Zealand", "Neuseeland", "nz"),
    ("fj", "oceania", "Fiji", "Fidschi", "fj"),
    ("pg", "oceania", "Papua New Guinea", "Papua-Neuguinea", "pg"),
]


def plant(
    id_: str,
    country_ids: list[str],
    name_en: str,
    name_de: str,
    scientific: str,
    family: str,
    parts: str,
    habitat: str,
    uses_en: str,
    uses_de: str,
    compounds: str,
    prep: str,
    cautions: str,
    flowering: str,
    history: str,
) -> dict:
    return {
        "id": id_,
        "countryIds": country_ids,
        "nameEn": name_en,
        "nameDe": name_de,
        "scientificName": scientific,
        "family": family,
        "partsUsed": parts,
        "habitat": habitat,
        "traditionalUsesEn": uses_en,
        "traditionalUsesDe": uses_de,
        "activeCompounds": compounds,
        "preparation": prep,
        "cautions": cautions,
        "floweringSeason": flowering,
        "historicalNotes": history,
    }


# Existing 21 kept with same IDs; plus many new ones
NEW_PLANTS = [
    plant(
        "nettle",
        ["de", "gb", "at", "pl"],
        "Stinging Nettle",
        "Große Brennnessel",
        "Urtica dioica",
        "Urticaceae",
        "Leaves, root",
        "Temperate Europe and Asia; nitrogen-rich soils, roadsides, woods.",
        "Traditional use for urinary tract support and joint discomfort; spring greens as food.",
        "Traditionell bei Harnwegsbeschwerden und Gelenkbeschwerden; Frühlingsgemüse.",
        "Flavonoids, minerals, amines (histamine in fresh hairs), sterols in root",
        "Cooked leaves, dried leaf tea, root extracts.",
        "Fresh plant stings. Seek advice for root extracts and with medications.",
        "June–September",
        "Long staple of European folk medicine and cuisine once cooked.",
    ),
    plant(
        "lemon-balm",
        ["de", "at", "fr", "gb"],
        "Lemon Balm",
        "Zitronenmelisse",
        "Melissa officinalis",
        "Lamiaceae",
        "Leaves",
        "Mediterranean origin; cultivated across temperate Europe.",
        "Mild restlessness and sleep difficulty; digestive discomfort; lemony culinary herb.",
        "Leichte Unruhe und Einschlafprobleme; Verdauungsbeschwerden; Küchenkraut.",
        "Essential oil (citral, citronellal), rosmarinic acid, flavonoids",
        "Fresh or dried leaf tea; culinary use; tinctures.",
        "Generally well tolerated as tea; essential oil diluted only.",
        "June–August",
        "Medieval monastic gardens; name Melissa from Greek for bee.",
    ),
    plant(
        "yarrow",
        ["de", "at", "gb", "se"],
        "Yarrow",
        "Schafgarbe",
        "Achillea millefolium",
        "Asteraceae",
        "Flowering tops",
        "Meadows and roadsides across Europe and temperate Asia.",
        "Traditional use for mild digestive complaints and as a diaphoretic tea in colds.",
        "Traditionell bei leichten Verdauungsbeschwerden und als schweißtreibender Tee bei Erkältung.",
        "Essential oil, sesquiterpene lactones, flavonoids, tannins",
        "Flowering herb tea; compresses traditionally.",
        "Asteraceae allergy risk. Not for high-dose internal use in pregnancy without advice.",
        "June–September",
        "Named for Achilles in classical legend; widespread European folk herb.",
    ),
    plant(
        "dandelion",
        ["de", "fr", "gb", "pl", "us", "ca"],
        "Dandelion",
        "Löwenzahn",
        "Taraxacum officinale",
        "Asteraceae",
        "Leaves, root",
        "Cosmopolitan temperate weed of lawns, meadows, and roadsides.",
        "Bitter digestive tonic; traditional diuretic use of leaves; roasted root beverage.",
        "Bitterstoff für die Verdauung; traditionell harntreibende Blätter; geröstete Wurzel als Getränk.",
        "Sesquiterpene lactones, phenolic acids, inulin (root), potassium",
        "Leaf salad or tea; root decoction or roasted coffee substitute.",
        "Asteraceae allergy; bile duct obstruction needs medical care, not self-treatment.",
        "Mainly spring–autumn (region-dependent)",
        "Name from French dent-de-lion; globalized with European settlement.",
    ),
    plant(
        "calendula",
        ["de", "fr", "es", "it", "at"],
        "Calendula / Pot Marigold",
        "Ringelblume",
        "Calendula officinalis",
        "Asteraceae",
        "Flower heads",
        "Mediterranean origin; widely cultivated in temperate gardens.",
        "Topical traditional use for minor skin inflammation and wounds; mild oral mucosa rinse.",
        "Äußerlich traditionell bei leichten Hautentzündungen und Wunden; leichte Mundspülung.",
        "Triterpene alcohols, flavonoids, carotenoids, essential oil",
        "Infused oil, ointments, tea compresses; flower tea.",
        "Asteraceae allergy possible. For external and mild internal traditional use only.",
        "May–October",
        "Named for blooming with the calendar months; staple of European herb gardens.",
    ),
    plant(
        "fennel",
        ["it", "es", "gr", "fr", "tr"],
        "Fennel",
        "Fenchel",
        "Foeniculum vulgare",
        "Apiaceae",
        "Fruits (seeds), leaves",
        "Mediterranean coasts; cultivated worldwide.",
        "Digestive complaints, mild spasms and bloating; culinary spice and vegetable (Florence fennel).",
        "Verdauungsbeschwerden, leichte Krämpfe und Blähungen; Gewürz und Gemüse.",
        "Essential oil (anethole, fenchone), flavonoids",
        "Crushed fruit tea; culinary use; syrups for mild cough traditions.",
        "Essential oil concentrated—not for undiluted self-use. Pregnancy: professional advice for medicinal doses.",
        "July–October",
        "Classical Mediterranean food and medicine plant.",
    ),
    plant(
        "elderflower",
        ["de", "at", "gb", "pl", "hu"],
        "Elderflower",
        "Holunderblüten",
        "Sambucus nigra",
        "Viburnaceae (formerly Caprifoliaceae)",
        "Flowers; ripe berries (separate use)",
        "Edges of woods and hedgerows of Europe.",
        "Traditional diaphoretic tea for colds; cordials; berries used as food when cooked.",
        "Traditionell schweißtreibender Tee bei Erkältung; Sirupe; Beeren nur gekocht als Nahrung.",
        "Flavonoids, phenolic acids, triterpenes; berries: anthocyanins",
        "Flower infusion; cooked berry products. Uncooked green parts and raw berries can be unpleasant/toxic.",
        "Do not eat raw leaves, stems, or unripe berries. Cook berries thoroughly.",
        "May–July",
        "Deeply rooted in European folklore and seasonal foodways.",
    ),
    plant(
        "hop",
        ["de", "cz", "gb", "pl", "nl"],
        "Hop",
        "Hopfen",
        "Humulus lupulus",
        "Cannabaceae",
        "Female strobiles (cones)",
        "Temperate Europe and Asia; widely cultivated for brewing.",
        "Traditional calming tea for restlessness; bitter for digestion; brewing flavor.",
        "Traditionell beruhigender Tee bei Unruhe; Bitterstoff für die Verdauung; Bierwürze.",
        "Bitter acids (humulone, lupulone), essential oil, flavonoids (xanthohumol)",
        "Dried cone tea or pillows; brewing; extracts.",
        "May cause drowsiness. Occupational allergy in hop workers known.",
        "July–September",
        "Central to beer culture since medieval Europe.",
    ),
    plant(
        "arnica",
        ["ch", "de", "at", "fr"],
        "Arnica",
        "Arnika",
        "Arnica montana",
        "Asteraceae",
        "Flower heads (external preparations)",
        "Mountain meadows of Central Europe; protected in many areas; cultivated substitutes used.",
        "Traditional external use for bruises and muscle ache (ointments, gels).",
        "Traditionell äußerlich bei Prellungen und Muskelkater (Salben, Gele).",
        "Sesquiterpene lactones (helenalin derivatives), flavonoids, essential oil",
        "Diluted topical products only. Not for broken skin or internal self-medication.",
        "Toxic if swallowed. External use only as directed. Asteraceae allergy.",
        "June–August",
        "Alpine folk medicine; conservation concerns for wild collection.",
    ),
    plant(
        "milk-thistle",
        ["de", "it", "es", "gr", "tr"],
        "Milk Thistle",
        "Mariendistel",
        "Silybum marianum",
        "Asteraceae",
        "Ripe fruits (seeds)",
        "Mediterranean and SW Europe; naturalized elsewhere.",
        "Traditional support for digestive complaints related to the liver; modern standardized extracts studied.",
        "Traditionell bei verdauungsbedingten Beschwerden mit Bezug zur Leber; standardisierte Extrakte erforscht.",
        "Silymarin complex (silybin and related flavonolignans)",
        "Seed powder, capsules of standardized extract; tea less common for silymarin yield.",
        "Asteraceae allergy. Not a substitute for medical care in liver disease—seek professional advice.",
        "June–August",
        "Medieval Christian legend of Mary’s milk on the leaves; pharmacognosy staple.",
    ),
    plant(
        "oregano",
        ["gr", "it", "tr", "es"],
        "Oregano",
        "Oregano / Dost",
        "Origanum vulgare",
        "Lamiaceae",
        "Aerial parts",
        "Mediterranean hillsides; widely cultivated.",
        "Culinary herb; traditional teas for mild digestive and cold-related comfort.",
        "Küchenkraut; traditionelle Tees bei leichten Verdauungs- und Erkältungsbeschwerden.",
        "Essential oil (carvacrol, thymol—chemotype dependent), flavonoids",
        "Dried herb culinary and tea; diluted essential oil external/aromatic only.",
        "Essential oil potent—dilute. Chemotypes vary widely.",
        "June–September",
        "Name from Greek oros ganos (joy of the mountain).",
    ),
    plant(
        "bay-laurel",
        ["tr", "gr", "it", "pt"],
        "Bay Laurel",
        "Lorbeer",
        "Laurus nobilis",
        "Lauraceae",
        "Leaves",
        "Mediterranean scrub; cultivated ornamental and culinary tree.",
        "Culinary seasoning; traditional digestive teas in Mediterranean folk practice.",
        "Küchengewürz; traditionelle Verdauungstees im Mittelmeerraum.",
        "Essential oil (1,8-cineole, others), sesquiterpene lactones",
        "Dried leaves in cooking; occasional leaf infusion.",
        "Do not confuse with cherry laurel (Prunus laurocerasus), which is toxic. Essential oil not for casual internal use.",
        "Spring (small yellow flowers)",
        "Symbol of victory in classical antiquity; Apollo’s plant in myth.",
    ),
    plant(
        "juniper",
        ["de", "at", "se", "no", "pl"],
        "Juniper",
        "Wacholder",
        "Juniperus communis",
        "Cupressaceae",
        "Ripe berry-like cones",
        "Heaths, mountains, and open woods of Europe and northern Asia.",
        "Traditional digestive and diuretic culinary spice; gin flavoring.",
        "Traditionell verdauungsförderndes und harntreibendes Gewürz; Gin-Aroma.",
        "Essential oil (α-pinene, others), sugars, resin",
        "Crushed berries in cooking and tea (short courses traditionally).",
        "Avoid high doses and prolonged use; not for kidney disease or pregnancy without advice.",
        "Cones ripen over 2–3 years",
        "Ancient European spice and ritual plant.",
    ),
    plant(
        "birch",
        ["se", "no", "pl", "de", "fi"],
        "Silver Birch",
        "Hänge-Birke",
        "Betula pendula",
        "Betulaceae",
        "Leaves",
        "Temperate and boreal Europe and Asia.",
        "Traditional leaf tea as a mild diuretic for flushing the urinary tract.",
        "Traditioneller Blättertee als mildes Diuretikum zur Durchspülung der Harnwege.",
        "Flavonoids, saponins, essential oil traces, vitamin C",
        "Dried leaf infusion; birch water (sap) as seasonal beverage in north Europe.",
        "Adequate fluid intake when using diuretic teas. Seek care for UTI symptoms.",
        "April–May (catkins)",
        "Central tree in northern European culture and folk medicine.",
    ),
    plant(
        "ashwagandha",
        ["in", "np"],
        "Ashwagandha",
        "Schlafbeere / Ashwagandha",
        "Withania somnifera",
        "Solanaceae",
        "Root",
        "Dry regions of India, Middle East, and Africa; extensively cultivated in India.",
        "Ayurvedic rasayana (rejuvenative) tradition for stress and vitality; modern adaptogen research ongoing.",
        "Ayurvedische Rasayana-Tradition bei Stress und Vitalität; moderne Adaptogen-Forschung.",
        "Withanolides, alkaloids, sitoindosides",
        "Powdered root, standardized extracts, milk decoctions in classical recipes.",
        "May interact with sedatives, thyroid, and immunosuppressant drugs. Pregnancy: avoid medicinal use without advice. Nightshade family.",
        "Year-round in tropics; flowers small greenish",
        "Sanskrit name refers to horse-like strength/scent; cornerstone of Ayurveda.",
    ),
    plant(
        "holy-basil",
        ["in", "th", "np"],
        "Holy Basil / Tulsi",
        "Indisches Basilikum / Tulsi",
        "Ocimum tenuiflorum (syn. O. sanctum)",
        "Lamiaceae",
        "Leaves, flowering tops",
        "Indian subcontinent; sacred and culinary cultivation across South and SE Asia.",
        "Ayurvedic daily tonic tea; traditional use for stress and mild respiratory comfort.",
        "Ayurvedischer Alltagstee; traditionell bei Stress und leichten Atemwegsbeschwerden.",
        "Essential oil (eugenol chemotypes common), ursolic acid, flavonoids",
        "Fresh or dried leaf tea; culinary use in some regional dishes.",
        "Essential oil potent. May affect blood clotting and blood sugar—advice if on medication.",
        "Much of the year in warm climates",
        "Sacred plant in Hindu tradition; household courtyard plant in India.",
    ),
    plant(
        "cardamom",
        ["in", "lk", "gt"],
        "Green Cardamom",
        "Grüner Kardamom",
        "Elettaria cardamomum",
        "Zingiberaceae",
        "Fruit capsules / seeds",
        "Western Ghats of India and Sri Lanka; major production also in Guatemala.",
        "Culinary spice; traditional digestive aromatic in Ayurveda and Middle Eastern coffee.",
        "Küchengewürz; traditionell verdauungsförderndes Aroma in Ayurveda und arabischem Kaffee.",
        "Essential oil (1,8-cineole, terpinyl acetate, others)",
        "Whole or ground seeds in food and chai; occasional digestive tea.",
        "Food amounts safe for most people. Concentrated oil not for casual internal use.",
        "Rarely flowers outside humid tropics",
        "One of the world’s most valuable spices by weight historically.",
    ),
    plant(
        "cinnamon",
        ["lk", "in", "id", "vn"],
        "Ceylon Cinnamon",
        "Ceylon-Zimt",
        "Cinnamomum verum (syn. C. zeylanicum)",
        "Lauraceae",
        "Inner bark",
        "Sri Lanka native; cultivated in tropics of Asia.",
        "Culinary spice; traditional digestive and warming remedy in many systems.",
        "Küchengewürz; traditionell verdauungsfördernd und wärmend in vielen Systemen.",
        "Essential oil (cinnamaldehyde, eugenol—profile differs from cassia), coumarin (low in true cinnamon)",
        "Quills or powder in food; tea; extracts.",
        "Cassia cinnamon (C. cassia) is higher in coumarin—limit high chronic intake. True Ceylon preferred for frequent use.",
        "Unknown (cultivated trees)",
        "Ancient spice trade staple from Sri Lanka (Ceylon).",
    ),
    plant(
        "clove",
        ["id", "my", "mg"],
        "Clove",
        "Gewürznelke",
        "Syzygium aromaticum",
        "Myrtaceae",
        "Dried flower buds",
        "Maluku Islands (Indonesia) origin; cultivated in tropics including Madagascar and Zanzibar historically.",
        "Culinary spice; traditional local use for toothache (eugenol); warming digestive aromatic.",
        "Küchengewürz; traditionell bei Zahnschmerzen (Eugenol); wärmendes Verdauungsaroma.",
        "Essential oil (eugenol major), tannins",
        "Whole buds in cooking; diluted clove oil for dental tradition under guidance.",
        "Clove oil is caustic undiluted. Not for infants. High doses toxic.",
        "Bud harvest timed before opening",
        "Drove colonial spice wars; once worth more than gold by weight in Europe.",
    ),
    plant(
        "star-anise",
        ["cn", "vn"],
        "Star Anise",
        "Sternanis",
        "Illicium verum",
        "Schisandraceae",
        "Ripe fruit (star-shaped carpels)",
        "Southern China and Vietnam; humid subtropical hills.",
        "Culinary spice in Chinese five-spice and pho; traditional cold/digestive teas.",
        "Küchengewürz (Fünf-Gewürze, Pho); traditionelle Erkältungs- und Verdauungstees.",
        "Essential oil (trans-anethole major)",
        "Whole stars in broths and tea; ground spice.",
        "Do not confuse with toxic Japanese star anise (Illicium anisatum). Use culinary-grade I. verum only.",
        "Unknown",
        "Source of shikimic acid historically used in pharmaceutical synthesis pathways.",
    ),
    plant(
        "licorice",
        ["cn", "ir", "tr", "es"],
        "Licorice",
        "Süßholz",
        "Glycyrrhiza glabra",
        "Fabaceae",
        "Root and stolons",
        "Mediterranean to Central Asia; Chinese G. uralensis also used in TCM.",
        "Traditional demulcent for sore throat and digestive comfort; major TCM formula herb (gan cao).",
        "Traditionell reizmildernd bei Halsschmerzen und Verdauung; wichtige TCM-Pflanze (Gancao).",
        "Glycyrrhizin (saponin), flavonoids (liquiritin), coumarins",
        "Decoction, lozenges, extracts; often combined in formulas.",
        "Can raise blood pressure and lower potassium with prolonged high intake. Avoid excess if hypertensive; drug interactions possible.",
        "Summer",
        "One of the oldest continuously used medicinal roots in Eurasia.",
    ),
    plant(
        "ginkgo",
        ["cn", "jp", "kr", "de"],
        "Ginkgo",
        "Ginkgo",
        "Ginkgo biloba",
        "Ginkgoaceae",
        "Leaves (standardized extracts)",
        "Native relict of China; planted worldwide as street tree.",
        "Modern phytotherapy uses standardized leaf extracts for cognitive and circulatory support claims under product guidance.",
        "In der Phytotherapie standardisierte Blattextrakte bei kognitiver und zirkulatorischer Unterstützung (laut Produkt).",
        "Ginkgolides, bilobalide, flavonoids",
        "Standardized dry extracts (capsules/tablets); tea less standardized.",
        "May increase bleeding risk with anticoagulants. Fresh seeds toxic if misprepared. Use standardized products as labeled.",
        "Spring (trees dioecious)",
        "Living fossil; sacred in East Asian temple plantings.",
    ),
    plant(
        "schisandra",
        ["cn", "kr", "jp"],
        "Schisandra",
        "Chinesisches Spaltkölbchen",
        "Schisandra chinensis",
        "Schisandraceae",
        "Ripe berries",
        "Forests of northern China, Korea, and Russian Far East.",
        "TCM adaptogenic berry (wu wei zi, five-flavor fruit) for fatigue and resilience traditions.",
        "TCM-Adaptogenbeere (Wuweizi) bei Müdigkeit und Widerstandskraft.",
        "Lignans (schisandrin and related), organic acids, essential oil",
        "Dried berry decoctions, tinctures, modern extracts.",
        "May interact with drugs via liver enzymes. Professional guidance for therapeutic use.",
        "Summer",
        "Classic Taoist tonic fruit of northern Chinese medicine.",
    ),
    plant(
        "gotu-kola",
        ["in", "lk", "id", "my"],
        "Gotu Kola",
        "Indischer Wassernabel",
        "Centella asiatica",
        "Apiaceae",
        "Aerial parts",
        "Tropical wetlands of Asia and beyond; common in India and SE Asia.",
        "Ayurvedic and SE Asian use for skin and mental clarity traditions; culinary greens in some regions.",
        "Ayurvedische und südostasiatische Nutzung für Haut und geistige Klarheit; regional als Blattgemüse.",
        "Triterpene saponins (asiaticoside, madecassoside), flavonoids",
        "Fresh leaves, dried herb tea, topical and oral extracts.",
        "Generally food-like in culinary amounts; concentrated extracts—follow product advice.",
        "Much of the year in tropics",
        "Sanskrit mandukaparni; common market green in parts of Asia.",
    ),
    plant(
        "neem",
        ["in", "lk", "my"],
        "Neem",
        "Niembaum",
        "Azadirachta indica",
        "Meliaceae",
        "Leaves, seed oil (external traditions vary)",
        "Indian subcontinent; drought-tolerant tree of dry tropics.",
        "Traditional Indian use of leaves for skin and oral hygiene; seed oil as agricultural pesticide (azadirachtin).",
        "Traditionelle indische Nutzung der Blätter für Haut und Mundhygiene; Samenöl als landwirtschaftliches Insektizid.",
        "Limonoids (azadirachtin in seeds), nimbin, flavonoids",
        "Leaf pastes and teas in folk practice; oil external; not a casual internal medicine.",
        "Internal use of concentrated products can be unsafe, especially in children. Prefer external/traditional guidance.",
        "Seasonal (region-dependent)",
        "Village pharmacy tree of rural India; WHO and ethnobotany frequently cite it.",
    ),
    plant(
        "moringa",
        ["in", "ph", "ng", "ke"],
        "Moringa / Drumstick Tree",
        "Meerrettichbaum",
        "Moringa oleifera",
        "Moringaceae",
        "Leaves, pods, seeds",
        "NW India origin; cultivated across tropics of Asia and Africa.",
        "Nutrient-dense leaf vegetable; traditional uses for nutrition and general wellness in tropical folk systems.",
        "Nährstoffreiches Blattgemüse; traditionell für Ernährung und Allgemeinbefinden in tropischen Volksheilkunden.",
        "Vitamins, minerals, isothiocyanates, flavonoids (composition varies with soil)",
        "Cooked leaves and pods; dried leaf powder; seed oil (ben oil).",
        "Root and bark not for casual use (alkaline toxins in some parts). Prefer culinary leaf/pod use.",
        "Year-round in tropics",
        "Promoted in modern nutrition programs; ancient Ayurvedic mentions.",
    ),
    plant(
        "saffron",
        ["ir", "es", "in", "gr"],
        "Saffron",
        "Safran",
        "Crocus sativus",
        "Iridaceae",
        "Dried stigmas",
        "Cultivated sterile triploid; major production in Iran, also Spain, Kashmir, Greece.",
        "Culinary spice and colorant; traditional mood and digestive aromatic in Persian and Mediterranean medicine.",
        "Küchengewürz und Färbemittel; traditionell stimmungs- und verdauungsbezogen in persischer und mediterraner Medizin.",
        "Crocins, picrocrocin, safranal",
        "Threads steeped in warm liquid for food; small culinary pinches.",
        "Very expensive—adulteration common. Extremely high doses toxic. Culinary amounts only unless supervised.",
        "Autumn",
        "Historically worth its weight in gold; hand-harvested stigmas.",
    ),
    plant(
        "wasabi",
        ["jp"],
        "Wasabi",
        "Wasabi",
        "Eutrema japonicum (syn. Wasabia japonica)",
        "Brassicaceae",
        "Rhizome",
        "Cool mountain streams of Japan; difficult cultivation.",
        "Culinary pungent condiment; traditional Japanese accompaniment to raw fish.",
        "Scharfes Würzmittel der japanischen Küche; traditionell zu rohem Fisch.",
        "Isothiocyanates (allyl isothiocyanate related compounds from glucosinolates)",
        "Freshly grated rhizome; many commercial pastes are horseradish-based substitutes.",
        "Pungent vapors irritate eyes and sinuses. Food use only.",
        "Unknown (cultivated)",
        "True wasabi scarce and prized; often replaced by dyed horseradish abroad.",
    ),
    plant(
        "perilla",
        ["jp", "kr", "cn", "vn"],
        "Perilla / Shiso",
        "Schwarznessel / Shiso",
        "Perilla frutescens",
        "Lamiaceae",
        "Leaves, seeds",
        "East Asia; culinary herb in Japan, Korea, Vietnam, China.",
        "Culinary herb (sushi garnish, kimchi, oils); traditional East Asian medicinal food uses vary by cultivar.",
        "Küchenkraut (Sushi, Kimchi, Öle); traditionelle ostasiatische Nutzungen je nach Sorte.",
        "Essential oil (perillaldehyde chemotypes), rosmarinic acid, anthocyanins (red forms)",
        "Fresh leaves; seed oil; pickled leaves.",
        "Rare pulmonary issues linked to long high intake of seed oil in animals—normal culinary use typical.",
        "Summer–autumn",
        "Red and green chemotypes shape regional cuisines.",
    ),
    plant(
        "galangal",
        ["th", "id", "my", "vn"],
        "Greater Galangal",
        "Thai-Ingwer / Galanga",
        "Alpinia galanga",
        "Zingiberaceae",
        "Rhizome",
        "SE Asia; essential in Thai and Indonesian cooking.",
        "Culinary aromatic rhizome; traditional digestive and cold-related uses in SE Asian folk medicine.",
        "Kulinarisches Aromarhizom; traditionell bei Verdauung und Erkältung in SE-Asien.",
        "Essential oil (1,8-cineole, others), galangin flavonoids",
        "Fresh slices in soups and curries; dried powder; teas.",
        "Culinary amounts generally safe. Medicinal concentrates—professional guidance.",
        "Rare outside tropics",
        "Distinct from lesser galangal (Alpinia officinarum) used more in Chinese medicine.",
    ),
    plant(
        "kava",
        ["fj", "pg"],
        "Kava",
        "Kava",
        "Piper methysticum",
        "Piperaceae",
        "Root and rhizome",
        "Pacific islands; cultivated in Fiji, Vanuatu, PNG, Samoa, etc.",
        "Traditional Pacific ceremonial beverage for social relaxation and mild anxiolysis.",
        "Traditionelles pazifisches Zeremoniengetränk zur sozialen Entspannung.",
        "Kavalactones (kavain, methysticin, and others)",
        "Water extraction of peeled root; modern extracts (regulatory status varies by country).",
        "Liver toxicity reports with some products—many jurisdictions restrict. Not with alcohol or hepatotoxic drugs. Not for pregnancy.",
        "Unknown (cultivated clones rarely seed)",
        "Central to Melanesian and Polynesian social ritual for centuries.",
    ),
    plant(
        "goldenseal",
        ["us", "ca"],
        "Goldenseal",
        "Kanadische Orangenwurzel",
        "Hydrastis canadensis",
        "Ranunculaceae",
        "Rhizome and roots",
        "Eastern North American rich woods; overharvested in wild; cultivated increasingly.",
        "Traditional Native American and later Eclectic use for mucous membrane complaints; bitter tonic.",
        "Traditionelle Nutzung indigener Völker und späterer Eclectics bei Schleimhautbeschwerden; Bittertonikum.",
        "Isoquinoline alkaloids (berberine, hydrastine)",
        "Dried root tea or tincture (professional products).",
        "Not for pregnancy. Alkaloids potent; drug interactions possible. Conservation: prefer cultivated sources.",
        "Spring",
        "Among the most famous and conservation-sensitive North American medicinals.",
    ),
    plant(
        "american-ginseng",
        ["us", "ca"],
        "American Ginseng",
        "Amerikanischer Ginseng",
        "Panax quinquefolius",
        "Araliaceae",
        "Root",
        "Deciduous forests of eastern North America; heavily wild-harvest regulated.",
        "Traditional tonic parallel to Asian ginseng; major export to Chinese markets historically.",
        "Traditionelles Tonikum parallel zum asiatischen Ginseng; historisch großer Export nach China.",
        "Ginsenosides (profile differs from P. ginseng)",
        "Dried root, extracts, teas.",
        "Similar cautions as Asian ginseng regarding drugs and long self-medication. CITES-related trade rules apply to wild roots.",
        "Summer",
        "Drove 18th–19th century trade from Appalachia to China.",
    ),
    plant(
        "witch-hazel",
        ["us", "ca"],
        "Witch Hazel",
        "Virginische Zaubernuss",
        "Hamamelis virginiana",
        "Hamamelidaceae",
        "Leaves and bark (distillate water widely sold)",
        "Eastern North American woodlands.",
        "Traditional astringent for skin; modern witch hazel water as topical toner after distillation.",
        "Traditionelles Adstringens für die Haut; modernes Hamameliswasser als äußerliches Toner.",
        "Tannins (hamamelitannin), flavonoids; distillate mainly aqueous aromatics",
        "Topical distilled witch hazel USP; leaf/bark decoctions traditionally.",
        "External use preferred for commercial distillate. Internal tannin-rich preps can irritate.",
        "Autumn (unique late bloom)",
        "Name from Middle English wiche (pliable); Native and settler medicine.",
    ),
    plant(
        "saw-palmetto",
        ["us"],
        "Saw Palmetto",
        "Sägepalme",
        "Serenoa repens",
        "Arecaceae",
        "Ripe fruit",
        "Southeastern US coastal plains, especially Florida.",
        "Traditional and modern herbal use of berry extracts for urinary symptoms of benign prostatic hyperplasia (evidence mixed; medical diagnosis required).",
        "Traditionell und modern Beerenextrakte bei Harnbeschwerden der benignen Prostatahyperplasie (Evidenz gemischt; Diagnose nötig).",
        "Fatty acids, phytosterols",
        "Lipophilic extracts (capsules); traditional berry preparations.",
        "Not a substitute for prostate cancer screening. May interact with hormones. Professional advice.",
        "Spring",
        "Seminole and later Eclectic use; major US botanical industry crop.",
    ),
    plant(
        "black-cohosh",
        ["us", "ca"],
        "Black Cohosh",
        "Traubensilberkerze",
        "Actaea racemosa (syn. Cimicifuga racemosa)",
        "Ranunculaceae",
        "Rhizome and roots",
        "Eastern North American woodlands.",
        "Traditional Native American use; modern European phytotherapy for menopausal symptoms (products standardized).",
        "Traditionelle indigene Nutzung; moderne europäische Phytotherapie bei Wechseljahresbeschwerden.",
        "Triterpene glycosides, phenolic acids; exact actives debated",
        "Dried root extracts and tablets under product guidance.",
        "Rare liver issues reported—stop if jaundice. Not for pregnancy. Professional advice for menopause care.",
        "Summer",
        "Important Appalachian medicinal trade plant.",
    ),
    plant(
        "vanilla",
        ["mx", "mg", "id"],
        "Vanilla",
        "Gewürzvanille",
        "Vanilla planifolia",
        "Orchidaceae",
        "Cured seed pods (beans)",
        "Mesoamerican origin; major production in Madagascar, Indonesia, Mexico.",
        "Culinary flavoring; traditional Mesoamerican use with cacao beverages.",
        "Küchenaroma; traditionell mesoamerikanisch mit Kakao-Getränken.",
        "Vanillin and related phenolics (develop during curing)",
        "Extracts and whole beans in food; not typically a medicinal tea.",
        "Food use. Synthetic vanillin common in cheap products.",
        "Epiphytic orchid; flowers hand-pollinated in cultivation",
        "Totonac and Aztec heritage; second-most expensive spice after saffron often.",
    ),
    plant(
        "epazote",
        ["mx", "gt"],
        "Epazote",
        "Epazote / Jesuitentee",
        "Dysphania ambrosioides (syn. Chenopodium ambrosioides)",
        "Amaranthaceae",
        "Leaves",
        "Mexico and Central America; naturalized in warm regions.",
        "Culinary herb with beans in Mexican cooking; traditional antiparasitic folk use (caution).",
        "Küchenkraut zu Bohnen in Mexiko; traditionell gegen Parasiten (Vorsicht).",
        "Essential oil (ascaridole—variable, potentially toxic), terpenes",
        "Fresh leaves cooked with food in small culinary amounts.",
        "Essential oil and high medicinal doses toxic. Culinary leaf amounts only; avoid pregnancy medicinal use.",
        "Much of the year in tropics",
        "Nahuatl origin name; inseparable from Mexican bean cookery.",
    ),
    plant(
        "maca",
        ["pe", "bo"],
        "Maca",
        "Maca",
        "Lepidium meyenii",
        "Brassicaceae",
        "Hypocotyl (root-like storage organ)",
        "High Andes of Peru (and Bolivia); extreme altitude cultivation.",
        "Andean traditional food and fertility/vitality tonic; modern powdered superfood export.",
        "Andine Traditionalspeise und Vitalitätstonikum; modernes Pulver-Exportprodukt.",
        "Macamides, glucosinolates, starches, minerals",
        "Dried powder in food and smoothies; gelatinized powders common.",
        "Food amounts typical. Hormonal claims need evidence-based medical context.",
        "Unknown (cultivated biennial)",
        "Inca-era highland staple of the Junín plateau.",
    ),
    plant(
        "cat-s-claw",
        ["pe", "br", "bo"],
        "Cat's Claw",
        "Katzenkralle",
        "Uncaria tomentosa",
        "Rubiaceae",
        "Bark, root bark",
        "Amazonian rainforest vines of Peru and neighboring countries.",
        "Traditional Asháninka and Amazonian use for inflammatory complaints; modern bark extracts.",
        "Traditionelle asháninka- und amazonische Nutzung bei Entzündungsbeschwerden; moderne Rindenextrakte.",
        "Oxindole alkaloids, triterpenes, polyphenols",
        "Bark decoctions and standardized extracts.",
        "May stimulate immune activity—caution with autoimmune disease and before surgery. Professional advice.",
        "Unknown",
        "Named for claw-like thorns; major Peruvian botanical export.",
    ),
    plant(
        "guayusa",
        ["ec", "pe", "co"],
        "Guayusa",
        "Guayusa",
        "Ilex guayusa",
        "Aquifoliaceae",
        "Leaves",
        "Upper Amazon of Ecuador, Peru, Colombia; cultivated by Kichwa communities.",
        "Traditional morning stimulant tea of Amazonian cultures; caffeine-containing holly like yerba mate.",
        "Traditioneller morgendlicher Anregungstee amazonischer Kulturen; koffeinhaltige Ilex-Art.",
        "Caffeine, theobromine, polyphenols",
        "Dried leaf infusion.",
        "Caffeine content—limit if sensitive. Hot beverage temperature cautions similar to mate.",
        "Unknown",
        "Sacred dawn drink in Kichwa tradition of the Ecuadorian Amazon.",
    ),
    plant(
        "boldo",
        ["cl", "pe", "ar"],
        "Boldo",
        "Boldo",
        "Peumus boldus",
        "Monimiaceae",
        "Leaves",
        "Central Chile sclerophyll forests; related use in neighboring regions.",
        "Traditional South American digestive bitter for liver/gallbladder discomfort traditions.",
        "Traditionelles südamerikanisches Verdauungsbitter bei Leber-/Gallebeschwerden.",
        "Boldine (aporphine alkaloid), essential oil (ascaridole traces possible), flavonoids",
        "Leaf tea (short courses traditionally); extracts.",
        "Not for bile duct obstruction or severe liver disease self-care. Essential oil not for internal use. Professional advice.",
        "Spring–summer (Southern Hemisphere)",
        "Mapuche and Chilean folk medicine heritage.",
    ),
    plant(
        "copaiba",
        ["br", "co", "pe"],
        "Copaiba",
        "Kopaiva",
        "Copaifera spp. (e.g. C. officinalis, C. langsdorffii)",
        "Fabaceae",
        "Oleo-resin from trunk",
        "Amazon and tropical South American forests.",
        "Traditional Amazonian use of balsam for wounds and inflammatory complaints; modern essential oil/resin products.",
        "Traditionelles amazonisches Balsam bei Wunden und Entzündungen; moderne Harz-/Ölprodukte.",
        "Sesquiterpenes (β-caryophyllene prominent), diterpenes",
        "Resin topically diluted; capsules of oil in commercial products under guidance.",
        "Quality varies. Patch-test topical use. Internal use only with professional products/advice.",
        "Unknown",
        "Colonial pharmacy balsam exported from Brazil for centuries.",
    ),
    plant(
        "honeybush",
        ["za"],
        "Honeybush",
        "Honigbusch",
        "Cyclopia spp. (e.g. C. intermedia)",
        "Fabaceae",
        "Leaves and stems (fermented or green)",
        "Fynbos of South Africa's Cape region.",
        "Traditional Cape herbal tea, caffeine-free, honey-like aroma; folk use for mild coughs.",
        "Traditioneller koffeinfreier Kap-Tee mit Honigaroma; volksmedizinisch bei leichtem Husten.",
        "Xanthones, mangiferin, polyphenols; virtually caffeine-free",
        "Oxidized or green leaf infusion.",
        "Generally safe as beverage in normal amounts.",
        "Spring (species-dependent)",
        "Sister industry to rooibos in South African fynbos agriculture.",
    ),
    plant(
        "hoodia",
        ["za"],
        "Hoodia",
        "Hoodia",
        "Hoodia gordonii",
        "Apocynaceae",
        "Stem (traditional San use)",
        "Arid Kalahari regions of southern Africa.",
        "Traditional San use as appetite suppressant on long hunts; modern supplements controversial.",
        "Traditionelle San-Nutzung als appetithemmend auf langen Jagden; moderne Supplements umstritten.",
        "P57 oxypregnane steroidal glycoside (studied), other glycosides",
        "Traditional fresh stem; commercial extracts (efficacy/safety debated).",
        "Evidence for weight loss weak; conservation and biopiracy concerns. Not a proven diet drug.",
        "Unknown",
        "Famous for benefit-sharing debates after patent controversies.",
    ),
    plant(
        "baobab",
        ["mg", "sn", "za", "ke"],
        "Baobab",
        "Affenbrotbaum",
        "Adansonia digitata (African); A. grandidieri etc. in Madagascar",
        "Malvaceae",
        "Fruit pulp, leaves",
        "Savannas of Africa and dry forests of Madagascar (other species).",
        "Fruit pulp as vitamin-C-rich food; traditional leaf vegetable; cultural keystone tree.",
        "Fruchtfleisch als vitamin-C-reiche Nahrung; traditionelles Blattgemüse; Kulturbaum.",
        "Vitamin C, fiber, polyphenols in pulp; leaves: mucilage, minerals",
        "Dried fruit powder in food and drinks; cooked leaves.",
        "Food use. Species protected in some ranges—sustainable harvest.",
        "Species-dependent",
        "Tree of life in many African oral traditions.",
    ),
    plant(
        "hibiscus",
        ["eg", "sd", "ng", "mx", "jm"],
        "Roselle / Hibiscus",
        "Roselle / Hibiskus",
        "Hibiscus sabdariffa",
        "Malvaceae",
        "Fleshy calyces",
        "Tropical Africa origin; major drinks culture in Egypt (karkadeh), West Africa, Caribbean, Mexico (jamaica).",
        "Tart caffeine-free beverage; traditional cooling drink; studied for mild blood-pressure effects in some trials.",
        "Säuerliches koffeinfreies Getränk; traditionell kühlend; in Studien teils bei Blutdruck untersucht.",
        "Organic acids (hibiscus acid), anthocyanins, flavonoids",
        "Dried calyx infusion (hot or cold).",
        "May lower blood pressure—monitor if on antihypertensives. Food use generally safe.",
        "Short-day flowering in tropics",
        "Global diaspora beverage from African domesticates.",
    ),
    plant(
        "fenugreek",
        ["in", "eg", "ma", "et"],
        "Fenugreek",
        "Bockshornklee",
        "Trigonella foenum-graecum",
        "Fabaceae",
        "Seeds, leaves",
        "Mediterranean to India; ancient crop of Egypt and South Asia.",
        "Culinary spice and leafy green; traditional galactagogue and digestive bitter.",
        "Küchengewürz und Blattgemüse; traditionell milchbildend und verdauungsbitter.",
        "Steroidal saponins (diosgenin precursors), fiber, 4-hydroxyisoleucine",
        "Sprouted or cooked seeds; methi leaves; teas and powders.",
        "May lower blood sugar—caution with diabetes drugs. Maple-like body odor at high intake. Pregnancy medicinal doses: advice.",
        "Variable",
        "Found in Tutankhamun’s tomb; name means Greek hay.",
    ),
    plant(
        "myrrh",
        ["so", "et", "sa", "ye"],
        "Myrrh",
        "Myrrhe",
        "Commiphora myrrha (and related Commiphora spp.)",
        "Burseraceae",
        "Oleo-gum-resin",
        "Horn of Africa and southern Arabia arid woodlands.",
        "Incense and traditional oral/wound resins; classical embalming and biblical trade good.",
        "Räucherwerk und traditionelles Harz für Mund und Wunden; klassisches Handelsgut.",
        "Sesquiterpenes, furanosesquiterpenoids, resins",
        "Tincture diluted for oral rinses traditionally; incense; extracts.",
        "Not for pregnancy internally. Dilute topical/oral rinse products. Quality varies.",
        "Unknown",
        "Paired with frankincense in ancient Red Sea trade.",
    ),
    plant(
        "coffee",
        ["et", "co", "br", "vn", "id"],
        "Coffee",
        "Kaffee",
        "Coffea arabica / C. canephora",
        "Rubiaceae",
        "Roasted seeds (beans)",
        "Ethiopian highlands origin (arabica); tropical cultivation belt worldwide.",
        "Global stimulant beverage; traditional Ethiopian coffee ceremony; studied pharmacology of caffeine.",
        "Globales Anregungsgetränk; traditionelle äthiopische Kaffeezeremonie; Koffein-Pharmakologie gut untersucht.",
        "Caffeine, chlorogenic acids, trigonelline, diterpenes (cafestol, kahweol in unfiltered)",
        "Roasted and brewed; espresso, filter, traditional jebena pot.",
        "Caffeine: insomnia, anxiety, heart rhythm in sensitive people. Unfiltered coffee raises cholesterol in some studies.",
        "After rainy seasons (region-dependent)",
        "From Ethiopian forests to global commodity reshaping modern work culture.",
    ),
    plant(
        "shea",
        ["gh", "ng", "bf"],
        "Shea Tree",
        "Sheabaum",
        "Vitellaria paradoxa",
        "Sapotaceae",
        "Seed fat (shea butter)",
        "Sudanian savanna belt of West Africa.",
        "Traditional skin emollient and cooking fat; women’s cooperative economy plant.",
        "Traditionelles Hautpflege- und Kochfett; Wirtschaftspflanze von Frauenkooperativen.",
        "Stearic and oleic triglycerides, unsaponifiables (karitene, etc.)",
        "Cold-processed butter topical and culinary.",
        "Topical allergies rare but possible. Food use regional.",
        "Unknown",
        "Vital non-timber forest product of the Sahel–savanna.",
    ),
    plant(
        "kawakawa",
        ["nz"],
        "Kawakawa",
        "Kawakawa",
        "Piper excelsum",
        "Piperaceae",
        "Leaves",
        "Coastal and lowland forests of New Zealand.",
        "Traditional Māori rongoā for digestive and skin comfort; peppery leaf tea.",
        "Traditionelle māorische Rongoā bei Verdauungs- und Hautbeschwerden; pfeffriger Blättertee.",
        "Amides related to other Piper species, essential oil components",
        "Fresh or dried leaf infusions; topical oils in modern craft products.",
        "Traditional knowledge—use respectfully. Limited clinical data; culinary-like tea amounts common.",
        "Unknown",
        "Iconic New Zealand native pepper tree of rongoā Māori.",
    ),
    plant(
        "manuka",
        ["nz", "au"],
        "Mānuka",
        "Manuka",
        "Leptospermum scoparium",
        "Myrtaceae",
        "Leaves (tea); honey from nectar is a separate famous product",
        "New Zealand and SE Australia scrub and heath.",
        "Traditional Māori leaf use; global fame via mānuka honey antimicrobial research (methylglyoxal).",
        "Traditionelle māorische Blattnutzung; global bekannt durch Manuka-Honig-Forschung.",
        "Leaf essential oil (leptospermone and related); honey: MGO, DHA",
        "Leaf tea; honey as food (UMF/MGO graded products for quality).",
        "Honey not for infants under 1 year. Leaf oil diluted if used topically.",
        "Spring–summer",
        "Name from Māori; honey industry major NZ export.",
    ),
    plant(
        "eucalyptus",
        ["au", "pt", "br"],
        "Eucalyptus",
        "Eukalyptus",
        "Eucalyptus globulus (and other spp.)",
        "Myrtaceae",
        "Leaves; essential oil",
        "Australia native; planted worldwide in Mediterranean and subtropical climates.",
        "Traditional Aboriginal and later pharmacy use of leaf oil for inhalation in colds.",
        "Traditionelle und spätere pharmazeutische Nutzung des Blattöls zur Inhalation bei Erkältung.",
        "Essential oil (1,8-cineole major in many spp.)",
        "Steam inhalation of diluted oil; lozenges; leaf infusions carefully.",
        "Essential oil toxic if swallowed; keep from children. Not for infants’ faces. Dilute always.",
        "Species-dependent",
        "Iconic Australian genus; global plantation timber and oil crop.",
    ),
    plant(
        "kakadu-plum",
        ["au"],
        "Kakadu Plum",
        "Kakadu-Pflaume",
        "Terminalia ferdinandiana",
        "Combretaceae",
        "Fruit",
        "Woodlands of northern Australia.",
        "Traditional Aboriginal food; exceptionally high natural vitamin C content studied scientifically.",
        "Traditionelle Aboriginal-Nahrung; wissenschaftlich sehr hoher Vitamin-C-Gehalt.",
        "Vitamin C (ascorbic acid) at very high levels, ellagic acid, polyphenols",
        "Fresh or processed fruit products; powders in modern foods.",
        "Food use. Respect Indigenous supply chains and benefit-sharing.",
        "Wet season fruiting",
        "Among the highest vitamin C fruits measured globally.",
    ),
    plant(
        "noni",
        ["id", "ph", "fj", "pg"],
        "Noni",
        "Noni",
        "Morinda citrifolia",
        "Rubiaceae",
        "Fruit",
        "Pacific and SE Asian coasts; pantropical.",
        "Traditional Polynesian and SE Asian use of fruit; modern juices marketed widely.",
        "Traditionelle polynesische und südostasiatische Fruchtnutzung; moderne Säfte.",
        "Iridoids (asperuloside), fatty acids, potassium; distinctive odor compounds",
        "Fermented or fresh juice; cooked fruit in some traditions.",
        "High potassium—caution in kidney disease. Evidence for many health claims limited.",
        "Year-round in tropics",
        "Canoe plant of Polynesian voyaging culture.",
    ),
    plant(
        "boswellia-serrata",
        ["in"],
        "Indian Frankincense",
        "Indischer Weihrauch",
        "Boswellia serrata",
        "Burseraceae",
        "Oleo-gum-resin",
        "Dry forests of India.",
        "Ayurvedic shallaki resin for joint inflammatory complaints; boswellic acids studied.",
        "Ayurvedisches Shallaki-Harz bei Gelenkentzündungen; Boswelliasäuren erforscht.",
        "Boswellic acids (AKBA and related)",
        "Resin extracts standardized for boswellic acids; incense less common than African frankincense.",
        "GI side effects possible. Professional advice for chronic joint disease.",
        "Unknown",
        "Distinct species from Somali B. sacra; major Ayurvedic anti-inflammatory resin.",
    ),
    plant(
        "andrographis",
        ["in", "th", "vn", "cn"],
        "Andrographis / King of Bitters",
        "Andrographis / Kalmegh",
        "Andrographis paniculata",
        "Acanthaceae",
        "Aerial parts",
        "South and SE Asia; common in Indian and Thai herbalism.",
        "Intensely bitter traditional herb for feverish colds in Ayurveda and Thai medicine.",
        "Sehr bitteres traditionelles Kraut bei fiebrigen Erkältungen in Ayurveda und thailändischer Medizin.",
        "Andrographolide and related diterpene lactones",
        "Dried herb decoctions, standardized extracts.",
        "Very bitter. May affect fertility and immune drugs—professional advice. Not for pregnancy.",
        "Year-round in tropics",
        "Called king of bitters; WHO monographs discuss traditional cold use.",
    ),
    plant(
        "rhodiola",
        ["se", "no", "cn", "ru"],
        "Rhodiola / Golden Root",
        "Rosenwurz",
        "Rhodiola rosea",
        "Crassulaceae",
        "Rhizome and roots",
        "Arctic and alpine Eurasia; Scandinavian and Russian traditional use; Chinese related species too.",
        "Traditional adaptogen for fatigue in Viking-era and Soviet herbal traditions; modern extracts.",
        "Traditionelles Adaptogen bei Müdigkeit in skandinavischer und sowjetischer Tradition; moderne Extrakte.",
        "Rosavins, salidroside, tyrosol",
        "Standardized root extracts; traditional decoctions.",
        "May be stimulating—avoid late day if sleepless. Quality adulteration common. Professional advice for bipolar or stimulants.",
        "Summer",
        "Golden root of northern mountains; Arctic ethnobotany.",
    ),
    plant(
        "chia",
        ["mx", "gt"],
        "Chia",
        "Chia",
        "Salvia hispanica",
        "Lamiaceae",
        "Seeds",
        "Mesoamerica; major modern production in Latin America.",
        "Aztec staple seed; modern omega-3-rich food seed forming gels in liquid.",
        "Aztekische Stapelsaat; modernes omega-3-reiches Lebensmittel mit Gelbildung.",
        "α-linolenic acid, fiber, protein, minerals",
        "Soaked or dry seeds in food; beverages.",
        "Dry seeds can swell—take with fluid. Food use.",
        "Summer–autumn",
        "Revived global superfood from Nahua agriculture.",
    ),
    plant(
        "quinoa",
        ["pe", "bo", "ec"],
        "Quinoa",
        "Quinoa",
        "Chenopodium quinoa",
        "Amaranthaceae",
        "Seeds",
        "Andes; sacred Inca crop.",
        "Complete-protein grain-like seed; traditional Andean staple (not a classical medicinal herb but cultural plant food).",
        "Proteinreiches Pseudogetreide; andine Stapelnahrung.",
        "Proteins, saponins (seed coat—rinsed), minerals",
        "Rinsed and cooked seeds.",
        "Rinse to remove bitter saponins. Food use.",
        "Varies with altitude",
        "Mother grain of the Andes; global boom in 21st century.",
    ),
    plant(
        "damiana",
        ["mx", "us"],
        "Damiana",
        "Damiana",
        "Turnera diffusa",
        "Passifloraceae (formerly Turneraceae)",
        "Leaves",
        "Mexico and southwestern US dry scrub.",
        "Traditional Mexican leaf tea as mild tonic and reputed aphrodisiac; modern herbal specialty.",
        "Traditioneller mexikanischer Blättertee als mildes Tonikum; modern spezialisiertes Kraut.",
        "Essential oil, flavonoids, cyanogenic glycosides (low)",
        "Dried leaf tea or smoking blends historically (not recommended to smoke).",
        "Limited clinical data. Pregnancy: avoid. Prefer tea over smoking.",
        "Summer–autumn",
        "Documented in Mexican herbalism and 19th-century US Eclectic texts.",
    ),
    plant(
        "mullein",
        ["us", "gb", "de", "tr"],
        "Common Mullein",
        "Kleinblütige Königskerze / Kleinblütiges Wollkraut",
        "Verbascum thapsus",
        "Scrophulariaceae",
        "Leaves, flowers",
        "Europe and Asia; naturalized widely in North America.",
        "Traditional respiratory demulcent leaf tea and flower oil for ear comfort traditions.",
        "Traditionell reizmildernder Blättertee bei Atemwegen; Blütenöl traditionell bei Ohrbeschwerden.",
        "Mucilage, saponins, flavonoids, iridoids",
        "Leaf tea strained well (hairs irritating); flower-infused oil external.",
        "Strain teas carefully. Ear symptoms need medical evaluation—do not delay care.",
        "June–September",
        "Torch-like biennial of roadsides; classical European and settler herb.",
    ),
    plant(
        "plantain-leaf",
        ["de", "gb", "us", "nz"],
        "Greater Plantain",
        "Breitwegerich",
        "Plantago major",
        "Plantaginaceae",
        "Leaves, seeds (related P. ovata is ispaghula)",
        "Cosmopolitan temperate weed of paths and lawns.",
        "Traditional leaf poultice for insect bites and minor wounds; demulcent leaf tea.",
        "Traditioneller Blattumschlag bei Insektenstichen und kleinen Wunden; reizmildernder Tee.",
        "Mucilage, iridoid glycosides (aucubin), flavonoids",
        "Crushed fresh leaf poultice; dried leaf tea.",
        "Generally safe topically and as mild tea. Wound infection needs medical care.",
        "May–September",
        "Called white man’s footprint where it spread with European paths.",
    ),
    plant(
        "marshmallow",
        ["de", "fr", "gb", "tr"],
        "Marshmallow",
        "Eibisch",
        "Althaea officinalis",
        "Malvaceae",
        "Root, leaves, flowers",
        "Salt marshes and damp soils of Europe and Western Asia.",
        "Classic demulcent for dry cough and irritated mucosa; root cold maceration traditional.",
        "Klassisches Schleimmittel bei trockenem Husten und gereizten Schleimhäuten; Wurzel-Kaltauszug.",
        "Mucilage polysaccharides, flavonoids",
        "Cold-water root maceration; leaf tea; syrups.",
        "May slow absorption of medicines—separate dosing. Very gentle herb generally.",
        "July–September",
        "Original source of confection marshmallow before sugar candy replaced it.",
    ),
    plant(
        "linden",
        ["de", "pl", "fr", "hu", "cz"],
        "Linden / Lime Tree",
        "Lindenblüten",
        "Tilia cordata / T. platyphyllos",
        "Malvaceae",
        "Flowers with bracts",
        "European parks, avenues, and woodlands.",
        "Traditional calming diaphoretic tea for colds and restlessness.",
        "Traditionell beruhigender, schweißtreibender Tee bei Erkältung und Unruhe.",
        "Flavonoids, mucilage, essential oil traces, tannins",
        "Flower tea (infusion).",
        "Rare allergy. Flowers should be fully dried to avoid fermentation issues.",
        "June–July",
        "Sacred and civic tree of Central Europe; summer honey source.",
    ),
    plant(
        "hawthorn",
        ["de", "gb", "fr", "pl"],
        "Hawthorn",
        "Weißdorn",
        "Crataegus monogyna / C. laevigata",
        "Rosaceae",
        "Leaves, flowers, berries",
        "Hedgerows and wood edges of Europe.",
        "Traditional European heart tonic herb; modern extracts used under medical herbal guidance for mild cardiac complaints.",
        "Traditionelles europäisches Herzmittel; moderne Extrakte unter fachlicher Leitung bei leichten Herzbeschwerden.",
        "Oligomeric procyanidins, flavonoids (hyperoside, vitexin derivatives)",
        "Flowering tops tea; standardized leaf-flower extracts.",
        "Heart symptoms require diagnosis. May potentiate heart drugs—medical supervision essential.",
        "May–June",
        "May blossom of British and German folklore; Commission E and ESCOP monographs exist.",
    ),
    plant(
        "garlic",
        ["cn", "in", "es", "it", "eg", "kr"],
        "Garlic",
        "Knoblauch",
        "Allium sativum",
        "Amaryllidaceae",
        "Bulb",
        "Central Asian origin; cultivated globally.",
        "Culinary staple; traditional cardiovascular and antimicrobial folk uses; allicin chemistry well studied.",
        "Küchengrundlage; traditionell bei Herz-Kreislauf und als antimikrobiell; Allicin gut untersucht.",
        "Alliin → allicin (when crushed), ajoenes, sulfur compounds",
        "Crushed raw or cooked cloves; aged extracts; powders.",
        "Increases bleeding risk with anticoagulants. GI upset raw. Stop before surgery as advised.",
        "Summer (scapes)",
        "Among the oldest cultivated medicinal-culinary bulbs.",
    ),
    plant(
        "onion",
        ["cn", "in", "eg", "us", "nl"],
        "Onion",
        "Küchenzwiebel",
        "Allium cepa",
        "Amaryllidaceae",
        "Bulb",
        "Central Asian domestication; global crop.",
        "Culinary vegetable; traditional cough syrups and poultices in folk medicine.",
        "Küchengemüse; traditionelle Hustensäfte und Umschläge in der Volksmedizin.",
        "Sulfur compounds, flavonoids (quercetin)",
        "Raw or cooked food; traditional honey-onion syrups.",
        "Food use safe for most. Eye irritation when cutting.",
        "Summer",
        "Fundamental Eurasian crop of cuisine and folk care.",
    ),
    plant(
        "papaya",
        ["mx", "br", "in", "ph", "ng"],
        "Papaya",
        "Papaya",
        "Carica papaya",
        "Caricaceae",
        "Fruit, leaves, latex (papain)",
        "Mesoamerican origin; pantropical fruit crop.",
        "Nutritious fruit; traditional leaf teas in some cultures; latex enzyme papain for digestion/meat tenderizing.",
        "Nährstoffreiche Frucht; traditionelle Blättertees; Latex-Enzym Papain.",
        "Papain and chymopapain (latex), carotenoids, vitamin C in fruit",
        "Ripe fruit food; green fruit cooked; commercial papain; leaf tea traditions vary.",
        "Latex can irritate skin and is abortifacient in folk use—avoid medicinal latex in pregnancy. Unripe fruit caution in pregnancy.",
        "Year-round tropics",
        "Spread with Columbian exchange across tropics.",
    ),
    ]


def main() -> None:
    countries = [
        {
            "id": cid,
            "continentId": cont,
            "nameEn": en,
            "nameDe": de,
            "flagCode": flag,
        }
        for cid, cont, en, de, flag in COUNTRIES
    ]
    (DATA / "countries.json").write_text(
        json.dumps(countries, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print(f"Wrote {len(countries)} countries")

    # Load existing plants
    existing_ids = []
    if (PLANTS_DIR / "ids.json").exists():
        existing_ids = json.loads((PLANTS_DIR / "ids.json").read_text(encoding="utf-8"))

    existing_map = {}
    for pid in existing_ids:
        path = PLANTS_DIR / f"{pid}.json"
        if path.exists():
            existing_map[pid] = json.loads(path.read_text(encoding="utf-8"))

    # Filter new plants: skip pure placeholders that already exist
    added = 0
    for p in NEW_PLANTS:
        if p["traditionalUsesEn"] == "placeholder":
            continue
        if p["id"] in existing_map:
            # optionally enrich countryIds
            old = existing_map[p["id"]]
            merged = sorted(set(old.get("countryIds", []) + p["countryIds"]))
            if merged != sorted(old.get("countryIds", [])):
                old["countryIds"] = merged
                (PLANTS_DIR / f"{p['id']}.json").write_text(
                    json.dumps(old, indent=2, ensure_ascii=False) + "\n",
                    encoding="utf-8",
                )
                print(f"Updated countries for {p['id']}: {merged}")
            continue
        (PLANTS_DIR / f"{p['id']}.json").write_text(
            json.dumps(p, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
        )
        existing_ids.append(p["id"])
        existing_map[p["id"]] = p
        added += 1
        print(f"Added {p['id']}")

    # Also expand country lists on some classic plants
    expansions = {
        "chamomile": ["de", "at", "pl", "hu", "cz"],
        "lavender": ["fr", "es", "it", "hr", "tr"],
        "ginger": ["in", "cn", "th", "id", "ng", "jm"],
        "turmeric": ["in", "id", "th"],
        "tea": ["cn", "in", "jp", "lk", "vn"],
        "aloe-vera": ["mx", "eg", "in", "za"],
        "cacao": ["mx", "br", "ec", "co", "gh"],
        "peppermint": ["gb", "de", "us", "ma"],
        "echinacea": ["us", "ca"],
        "rooibos": ["za"],
        "yerba-mate": ["ar", "br", "py"],
        "passionflower": ["br", "us", "co"],
        "frankincense": ["so", "et", "om"] if False else ["so", "et", "sa"],
        "tea-tree": ["au"],
        "ginseng": ["kr", "cn"],
        "lemongrass": ["th", "in", "id", "ph"],
        "st-johns-wort": ["de", "at", "gb", "se"],
        "sage": ["it", "es", "gr", "hr"],
        "rosemary": ["es", "it", "fr", "pt", "hr"],
        "valerian": ["at", "de", "gb", "pl"],
        "thyme": ["gr", "es", "it", "fr", "tr"],
    }
    # fix frankincense - sa is saudi, omit invalid om
    for pid, cids in expansions.items():
        path = PLANTS_DIR / f"{pid}.json"
        if not path.exists():
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        # filter to known countries
        known = {c["id"] for c in countries}
        cids = [c for c in cids if c in known]
        data["countryIds"] = sorted(set(cids))
        path.write_text(json.dumps(data, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    # Rebuild ids preserving original order then new
    final_ids = []
    seen = set()
    for pid in existing_ids:
        if pid not in seen and (PLANTS_DIR / f"{pid}.json").exists():
            final_ids.append(pid)
            seen.add(pid)
    for path in sorted(PLANTS_DIR.glob("*.json")):
        if path.name in ("ids.json", "index.json"):
            continue
        pid = path.stem
        if pid not in seen:
            final_ids.append(pid)
            seen.add(pid)

    (PLANTS_DIR / "ids.json").write_text(
        json.dumps(final_ids, indent=2) + "\n", encoding="utf-8"
    )
    print(f"Total plants: {len(final_ids)} (added {added})")

    # Aggregate plants.json
    all_plants = [
        json.loads((PLANTS_DIR / f"{pid}.json").read_text(encoding="utf-8"))
        for pid in final_ids
    ]
    (DATA / "plants.json").write_text(
        json.dumps(all_plants, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    print("Wrote plants.json aggregate")


if __name__ == "__main__":
    main()
